### ISSUE TITLE
server will not start

### ISSUE THREAD

**Issue by ccgman123** [nponiros/sync_server#10]
I have cloned the repo, run npm install, run the init command in an empty directory, and attempted to start the server with --path to the empty directory

node is displaying an error that says Action not defined not supported

any suggestions ?

**Comment by nponiros** [comment]
In the readme I wrote `sync-server --path INIT/DIRECTORY/PATH` for the server start. I forgot to write the action. The correct command is `sync-server start --path INIT/DIRECTORY/PATH` (Fixed the readme now).

**Comment by ccgman123** [comment]
hahaha thank you sir working now.

**Comment by nponiros** [comment]
You're welcome. Closing the issue.
